trigger:
  branches:
    include:
      - master

variables:
  solutionDir: 'webappWithTests/Application/aspnet-core-dotnet-core'

pool:
 vmImage: 'windows-latest'

steps:
- script: pwd
  displayName: 'Gdzie jestesmy ?'

- script: dir
  displayName: 'Co jest w folderze?'

- script: dotnet build
  displayName: 'Budowanie app'
  workingDirectory: $(solutionDir)

- script: dotnet publish -o $(build.artifactStagingDirectory)
  displayName: 'Tworzenie i publikowanie -o $(build.artifactStagingDirectory)'
  workingDirectory: $(solutionDir)

- task: PublishPipelineArtifact@1
  displayName: 'Publikowanie pliku zip'
  inputs:
    targetPath: '@(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'