trigger:
- master

pool:
 vmImage: 'windows-latest'

steps:
- script: pwd
  displayName: 'Gdzie jestesmy ?'

- script: dir
  displayName: 'Co jest w folderze?'

- script: dotnet build
  displayName: 'Budowanie app'
  workingDirectory: 'webappWithTests/Application/aspnet-core-dotnet-core'

# - script: dotnet publish -o 