trigger:
  branches:
    include:
      - master

variables:
  solutionDir: 'webappWithTests/Application/aspnet-core-dotnet-core'

pool:
 vmImage: 'windows-latest'

steps:
- script: pwd
  displayName: 'Gdzie jestesmy ?'

- script: dir
  displayName: 'Co jest w folderze?'

- script: dotnet build
  displayName: 'Budowanie app'
  workingDirectory: $(solutionDir)

- script: dotnet publish -o $(build.artifactStagingDirectory)
  displayName: 'Tworzenie i publikowanie -o $(build.artifactStagingDirectory)'
  workingDirectory: $(solutionDir)

- task: PublishPipelineArtifact@1
  displayName: 'Publikowanie pliku  zip'
  inputs:
    # targetPath: '$(Pipeline.Workspace)'
    targetPath: '$(build.artifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(4eb40c76-f45b-4d01-a668-19892bd67f3e)'
    appType: 'webApp'
    appName: 'MS-Sample-dotnet'
    package: '$(System.DefaultWorkingDirectory)/**/drop.zip'
    deploymentMethod: 'zipDeploy'

# komentarz na probe
